Passive dependency support, removed cache, with vertical-only integration.
- Removed horizontal dependency support, and implemented vertical
  dependency integration.
- Removed dependency caching, as debugging revealed hardlinks will contain a pointer on
  disk to old files after the original file is overwritten.
  not change after file modification.
- Cleaned up output
- sbcreate now will synchronise the pacman database to the specified
  dependency

diff --git a/sbcreate b/sbcreate
--- a/sbcreate
+++ b/sbcreate
@@ -31,8 +31,6 @@
 
 MACHINE_ID=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 32 | head -n 1)
 	
-BASE_ROOT=$SANDBOX_BASE/deps/root/base
-
 main () {	
 
 	parse_args "$@"
@@ -46,6 +44,11 @@ main () {
 
 	if [[ -d $INSTANCE_ROOT ]] || [[ -d $INSTANCE_HOME ]]; then 
 		echo "Root or home directory for $SANDBOX exists. Aborting." 
+		exit 1
+	fi
+
+	if [[ ! -d $BASE_ROOT ]] && [[ $SANDBOX != "base" ]]; then
+		echo "Directory not found for $DEPEND root dependency."
 		exit 1
 	fi
 
@@ -64,21 +67,18 @@ main () {
 
 	if [[ $SANDBOX != "base" ]]; then
 	
-		echo "Initialising linker and link database.."
+		echo "Initialising linker.."
 
 		init_link	
-
-
-
 	fi
-
-	echo "Finalising chroot.."
-
-	finalise
 
 	echo "Cleaning up.."
 
 	cleanup
+
+	echo "Finalising chroot.."
+
+	finalise
 
 	echo "Process complete! Use sbexecute to configure $SANDBOX."
 }
@@ -86,32 +86,41 @@ main () {
 parse_args () {
 	ArGS=()
 	for var in "$@"; do
-		if [[ "$var" != *-* ]]; then 
-			SANDBOX=$var
-		elif [[ "$var" ==  "--dep" ]]; then
-			SWITCH=d$SWITCH
-		fi
+		case $var in 
+			--dep=*)
+				DEPEND=`echo $var | cut -c 7-`
+				;;	
+			--is-dep)
+				SWITCH=d$SWITCH
+				;;
+			*)
+				SANDBOX=$var
+				;;
+			esac
 	done
 }
 
 init_vars () {
 	PACMAN_CONFIG=pacman.base.conf	
 	PARAMS="--sandbox=$SANDBOX --root --exec"	
-	INSTANCE_ROOT=$SANDBOX_BASE/root/$SANDBOX
-	INSTANCE_HOME=$SANDBOX_BASE/home/$SANDBOX
+	INSTANCE_ROOT=$SANDBOX_BASE/base/root/$SANDBOX
+	INSTANCE_HOME=$SANDBOX_BASE/base/home/$SANDBOX
 	INSTANCE_DEP_LIST=$SANDBOX_BASE/etc/deps/$SANDBOX
 	INSTANCE_LINK=$SANDBOX_BASE/etc/db/$SANDBOX
-	INSTANCE_HOME=$SANDBOX_BASE/home/$SANDBOX
 
 	if [[ $SWITCH == *d* ]]; then
-		INSTANCE_ROOT=$SANDBOX_BASE/deps/root/$SANDBOX
-		INSTANCE_HOME=$SANDBOX_BASE/deps/home/$SANDBOX	
+		INSTANCE_ROOT=$SANDBOX_BASE/dep/root/$SANDBOX
+		INSTANCE_HOME=$SANDBOX_BASE/dep/home/$SANDBOX	
 		PARAMS="--dep $PARAMS"
 	fi
 	if [[ $SANDBOX == "base" ]]; then
 		PACMAN_CONFIG=pacman.conf
 	fi
-	
+	BASE_ROOT=$SANDBOX_BASE/dep/root/$DEPEND
+	if [[ ! $DEPEND ]]; then
+		BASE_ROOT=$SANDBOX_BASE/dep/root/base
+		DEPEND=base
+	fi	
 }
 
 
@@ -130,7 +139,7 @@ init_struct () {
 	#cp $XDG_DATA_HOME/sbscripts/template.new.sh $XDG_DATA_HOME/sbscripts/$SANDBOX.new.sh
 	echo "$MACHINE_ID" > $INSTANCE_ROOT/etc/machine-id
 	mkdir -p $INSTANCE_LINK
-	echo "base" > $INSTANCE_DEP_LIST
+	echo -e "## Generated by SBCREATE \n## TIMESTAMP: $(date "+%F %T") \n$DEPEND" > $INSTANCE_DEP_LIST
 }
 
 init_chroot () {	
@@ -143,19 +152,10 @@ init_chroot () {
 }
 
 init_link() {
-	link_create "$BASE_ROOT/usr/lib" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/base_lib
-	link_create "$BASE_ROOT/usr/lib32" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/base_lib32
-	link_create "$BASE_ROOT/usr/bin" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/base_bin
-	link_create "$BASE_ROOT/usr/share" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/base_share
-	
-	local dir=$PWD
-	cd $INSTANCE_LINK
-	sha256sum base_lib > $INSTANCE_LINK/base_lib.sha256
-	sha256sum base_bin > $INSTANCE_LINK/base_bin.sha256
-	sha256sum base_share > $INSTANCE_LINK/base_share.sha256
-	sha256sum base_lib32 > $INSTANCE_LINK/base_lib32.sha256
-
-	cd $dir
+	link_create "$BASE_ROOT/usr/lib" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/$DEPEND"_lib"
+	link_create "$BASE_ROOT/usr/lib32" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/$DEPEND"_lib32"
+	link_create "$BASE_ROOT/usr/bin" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/$DEPEND"_bin"
+	link_create "$BASE_ROOT/usr/share" "$INSTANCE_ROOT/usr/" > $INSTANCE_LINK/$DEPEND"_share"
 }
 
 
@@ -165,9 +165,6 @@ link_create() {
 		local file=${f%->*}
 		local filepath=$BASE_ROOT/usr/$file
 		if [[ -f $filepath ]] || [[ -L $filepath ]]; then
-			if [[ $file == "bin/[" ]]; then
-				continue
-			fi
 			echo $file
 		fi
 	done
@@ -178,7 +175,9 @@ finalise () {
 	sbexecute $PARAMS pacman-key --populate
 	sbexecute $PARAMS locale-gen
 	sbexecute $PARAMS update-ca-trust
-	mkdir -p /usr/lib32/
+	if [[ $DEPEND != "base" ]] && [[ $SANDBOX != "base" ]]; then
+		sbexecute $PARAMS pacman -Su --dbonly --noconfirm $(sbexecute --sandbox=$DEPEND --dep --root --exec pacman -Qqe | tail -n 2) 2>/dev/null
+	fi	
 }
 
 cleanup () {
